services:
  api:
    image: movie-api
    build:
      context: ../..
      dockerfile: src/api/Dockerfile
    container_name: movie-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
